on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hn_post
        with:
          HN_USERNAME: ${{ secrets.HN_USERNAME }}
          HN_PASSWORD: ${{ secrets.HN_PASSWORD }}
          POST_TITLE: "Test 3"
          POST_URL: https://encapsulate.me/helpful.html